name: flutter_skill
description: Give your AI Agent eyes and hands inside your Flutter app.
version: 0.4.0
homepage: https://github.com/ai-dashboad/flutter-skill
repository: https://github.com/ai-dashboad/flutter-skill
# publish_to: 'none' # Remove this when ready to publish to pub.dev

executables:
  flutter_skill: flutter_skill

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  vm_service: ^14.0.0
  http: ^1.1.0
  path: ^1.8.0
  logging: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^3.0.0
