import 'dart:convert';
import 'dart:io';
import 'package:http/http.dart' as http;

/// Automatically report errors to GitHub Issues
class ErrorReporter {
  final String owner;
  final String repo;
  final String? githubToken;

  ErrorReporter({
    required this.owner,
    required this.repo,
    this.githubToken,
  });

  /// Report an error with full diagnostic information
  Future<String?> reportError({
    required String errorType,
    required String errorMessage,
    required StackTrace stackTrace,
    Map<String, dynamic>? context,
    bool autoCreate = false,
  }) async {
    final diagnostics = _collectDiagnostics(
      errorType: errorType,
      errorMessage: errorMessage,
      stackTrace: stackTrace,
      context: context,
    );

    // Print diagnostic info to stderr for debugging
    stderr.writeln('\n╔════════════════════════════════════════════════════════╗');
    stderr.writeln('║  🐛 flutter-skill Error Detected                      ║');
    stderr.writeln('╚════════════════════════════════════════════════════════╝');
    stderr.writeln('');
    stderr.writeln('Error Type: $errorType');
    stderr.writeln('Message: $errorMessage');
    stderr.writeln('');
    stderr.writeln('Stack Trace:');
    stderr.writeln(stackTrace.toString().split('\n').take(10).join('\n'));
    stderr.writeln('');

    // Try to auto-create issue via GitHub API (if token available)
    if (autoCreate && githubToken != null) {
      final issueUrl = await _createGitHubIssue(
        title: '[$errorType] $errorMessage',
        body: _formatIssueBody(diagnostics),
      );

      if (issueUrl != null) {
        stderr.writeln('✅ GitHub Issue created: $issueUrl');
        return issueUrl;
      }
    }

    // Fallback: Auto-open browser with pre-filled issue (no config needed!)
    if (autoCreate) {
      final issueUrl = await _openBrowserWithIssue(
        title: '[$errorType] $errorMessage',
        body: _formatIssueBody(diagnostics),
      );
      if (issueUrl != null) {
        stderr.writeln('🌐 Opening browser to create issue...');
        stderr.writeln('   Please click "Submit new issue" in the browser');
        return issueUrl;
      }
    }

    stderr.writeln('To report this issue:');
    stderr.writeln('  1. Run: flutter_skill report-error');
    stderr.writeln('  2. Or visit: https://github.com/$owner/$repo/issues/new');
    stderr.writeln('');

    return null;
  }

  /// Collect comprehensive diagnostic information
  Map<String, dynamic> _collectDiagnostics({
    required String errorType,
    required String errorMessage,
    required StackTrace stackTrace,
    Map<String, dynamic>? context,
  }) {
    return {
      'error': {
        'type': errorType,
        'message': errorMessage,
        'stack_trace': stackTrace.toString(),
      },
      'environment': {
        'os': Platform.operatingSystem,
        'os_version': Platform.operatingSystemVersion,
        'dart_version': Platform.version,
        'flutter_skill_version': '0.2.14',
      },
      'context': context ?? {},
      'timestamp': DateTime.now().toIso8601String(),
    };
  }

  /// Format diagnostics as GitHub Issue body
  String _formatIssueBody(Map<String, dynamic> diagnostics) {
    final error = diagnostics['error'] as Map<String, dynamic>;
    final env = diagnostics['environment'] as Map<String, dynamic>;
    final context = diagnostics['context'] as Map<String, dynamic>;

    return '''
## Error Report

**Type:** `${error['type']}`
**Message:** ${error['message']}

## Environment

- OS: ${env['os']} (${env['os_version']})
- Dart: ${env['dart_version']}
- flutter-skill: ${env['flutter_skill_version']}

## Stack Trace

```
${error['stack_trace']}
```

## Context

```json
${JsonEncoder.withIndent('  ').convert(context)}
```

## Additional Information

<!-- Please add any additional context or screenshots here -->

---
*This issue was automatically generated by flutter-skill error reporter*
''';
  }

  /// Create a GitHub Issue using GitHub API
  Future<String?> _createGitHubIssue({
    required String title,
    required String body,
  }) async {
    if (githubToken == null) {
      stderr.writeln('⚠️  GitHub token not provided, skipping auto-creation');
      return null;
    }

    try {
      final response = await http.post(
        Uri.parse('https://api.github.com/repos/$owner/$repo/issues'),
        headers: {
          'Authorization': 'token $githubToken',
          'Accept': 'application/vnd.github.v3+json',
          'Content-Type': 'application/json',
        },
        body: jsonEncode({
          'title': title,
          'body': body,
          'labels': ['bug', 'auto-reported'],
        }),
      );

      if (response.statusCode == 201) {
        final issue = jsonDecode(response.body);
        return issue['html_url'] as String;
      } else {
        stderr.writeln('⚠️  Failed to create issue: ${response.statusCode}');
        stderr.writeln('Response: ${response.body}');
        return null;
      }
    } catch (e) {
      stderr.writeln('⚠️  Error creating GitHub issue: $e');
      return null;
    }
  }

  /// Open browser with pre-filled GitHub issue (no auth needed!)
  Future<String?> _openBrowserWithIssue({
    required String title,
    required String body,
  }) async {
    try {
      // URL-encode the title and body
      final encodedTitle = Uri.encodeComponent(title);
      final encodedBody = Uri.encodeComponent(body);

      // Construct GitHub issue creation URL with pre-filled content
      final issueUrl =
          'https://github.com/$owner/$repo/issues/new?title=$encodedTitle&body=$encodedBody';

      // Try to open in browser using platform-specific commands
      String command;
      if (Platform.isMacOS) {
        command = 'open';
      } else if (Platform.isLinux) {
        command = 'xdg-open';
      } else if (Platform.isWindows) {
        command = 'start';
      } else {
        stderr.writeln('⚠️  Cannot auto-open browser on this platform');
        stderr.writeln('Please visit: $issueUrl');
        return issueUrl;
      }

      // Open browser
      await Process.run(command, [issueUrl]);
      return issueUrl;
    } catch (e) {
      stderr.writeln('⚠️  Failed to open browser: $e');
      return null;
    }
  }

  /// Check for existing issues with similar error
  Future<List<Map<String, dynamic>>> findSimilarIssues(String errorType) async {
    try {
      final response = await http.get(
        Uri.parse(
          'https://api.github.com/search/issues?q=repo:$owner/$repo+is:issue+$errorType',
        ),
        headers: {
          'Accept': 'application/vnd.github.v3+json',
        },
      );

      if (response.statusCode == 200) {
        final data = jsonDecode(response.body);
        return (data['items'] as List)
            .map((item) => {
                  'title': item['title'],
                  'url': item['html_url'],
                  'state': item['state'],
                })
            .toList();
      }
    } catch (e) {
      // Ignore search errors
    }
    return [];
  }
}

/// Global error reporter instance
///
/// Configuration:
/// - Set GITHUB_TOKEN environment variable to enable auto-reporting
/// - Set FLUTTER_SKILL_AUTO_REPORT=true to automatically create issues
///
/// Example:
///   export GITHUB_TOKEN=ghp_xxxxx
///   export FLUTTER_SKILL_AUTO_REPORT=true
final errorReporter = ErrorReporter(
  owner: Platform.environment['FLUTTER_SKILL_REPO_OWNER'] ?? 'anthropics',
  repo: Platform.environment['FLUTTER_SKILL_REPO_NAME'] ?? 'flutter-skill',
  githubToken: Platform.environment['GITHUB_TOKEN'],
);
